### ISSUE TITLE
Only version 1.2.0 and 1.2.1

### ISSUE THREAD

**Issue by linusvdv** [BradBot1/BradsFabricApi#8]
The newer versions of BFAPI do not work for me. When I start a newer version, it still shows me the old version(1.2.1).

Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[14:14:51] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.1
[14:14:52] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.1
[14:14:52] [main/INFO]: Loading 4 mods:
	**- bfapi 1.2.1**
	- fabricloader 0.13.1
	- java 17
	- minecraft 1.18.1
[14:14:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/linus/Minecraft_Server_Livesteal/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[14:14:52] [main/INFO]: Compatibility level set to JAVA_16
**[14:14:57] [main/INFO]: Isn't BFAPI 1.3.1 funky?**
[14:14:57] [main/INFO]: Saved bfapi:permissions

----------------------------------------------------------------------------------------

I have a **Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz** computer and runs on **Ubuntu 20.04.3 LTS**.

If I want to run Lifesteal it shows me:
```
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[13:10:41] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.1
[13:10:41] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.1
[13:10:42] [main/WARN]: Mod resolution failed
[13:10:42] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE lifesteal 2.0.0 {depends bfapi @ [>=1.3.0]}, ROOT_FORCELOAD_SINGLE lifesteal 2.0.0]
[13:10:42] [main/INFO]: Reason: [HARD_DEP lifesteal 2.0.0 {depends bfapi @ [>=1.3.0]}]
[13:10:42] [main/INFO]: Fix: add [], remove [], replace [[bfapi 1.2.1] -> add:bfapi 1.3.0 ([[1.3.0,∞)])]
[13:10:42] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'BFAPI' (bfapi) 1.2.1 with version 1.3.0 or later.
Unmet dependency listing:
	 - Mod 'LifeSteal' (lifesteal) 2.0.0 requires version 1.3.0 or later of mod 'BFAPI' (bfapi), but only the wrong version is present: 1.2.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-server-launch.jar:?]

```

**Comment by BradBot1** [comment]
I forgot to build with the correct fv 🤦

**Comment by BradBot1** [comment]
You can get the latest version here
https://modrinth.com/mod/bfapi/version/bi51jjs5
this *should* work

**Comment by linusvdv** [comment]
Thank you!
